name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run RepoSwarm
        shell: bash
        run: |
          curl https://mise.run | sh
          curl -sSf https://temporal.download/cli.sh | bash
          
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          mise --version
          ls -la

          mise exec -- pip install temporalio pydantic GitPython requests anthropic boto3 pytest pytest-asyncio anyio
          mise install
          #mise run dev-dependencies
  
          mise investigate-one https://github.com/marketingcraze/PWA-LIVE

