name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          version: 2025.1.0        # optional, default latest
          install: true            # runs `mise install`
          cache: false              # enables tool caching

      - name: Install Temporal CLI
        uses: temporalio/setup-temporal@v0
        with:
          version: v0.12.0
      
      - name: Run Dependencies
        run: |
          mise run dev-dependencies
          mise exec -- pip install temporalio
          mise exec -- python -c "import temporalio; print(temporalio.__version__)"
          mise exec -- pip install pydantic
          mise exec -- python -c "import pydantic; print(pydantic.__version__)"
          mise exec -- pip install GitPython
          mise exec -- python -c "import git; print(git.__version__)"
    
      - name: Verify tools
        run: |
          ls -la
          node --version
          python --version
          go version
          temporal --version
          git --version

      - name: Start Temporal server (background)
        run: |
          temporal server start-dev --headless &
          sleep 5
    
      - name: Generate documents
        run: |
         # mise investigate-all
           mise investigate-one https://github.com/marketingcraze/PWA-DEV

     
